apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: default
  labels:
    app: httpd
spec:
  replicas: 5 # Starting with 2 replicas
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: ashish2706/argo-httpd-hairsalon:latest
        ports:
        - containerPort: 80
